version: '3.9'

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "8080:80" # Map port 80 inside the container to port 8080 on the host
    networks:
      - 	internal-network
    restart: unless-stopped

networks:
  internal-network:
    external: true
