version: '3.9'

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "8080:80" 
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    external: true
